// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc

import (
	"github.com/kolesnikovm/messenger/server/grpc/messenger"
	"github.com/kolesnikovm/messenger/usecase/message"
)

// Injectors from wire.go:

func InitializeServerBuilder() ServerBuilder {
	messageUseCase := message.New()
	handler := messenger.NewHandler(messageUseCase)
	streamServerInterceptor := NewInterceptor()
	serverBuilder := ServerBuilder{
		MessengerServer: handler,
		Interceptor:     streamServerInterceptor,
	}
	return serverBuilder
}
