// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/kolesnikovm/messenger/configs"
	"github.com/kolesnikovm/messenger/di"
	"github.com/kolesnikovm/messenger/server/grpc"
	"github.com/kolesnikovm/messenger/server/grpc/messenger"
	"github.com/kolesnikovm/messenger/usecase/message"
)

// Injectors from wire.go:

func InitializeApplication(conf configs.ServerConfig) *application {
	messageSender := di.ProvideNotifier(conf)
	messageUseCase := message.New(messageSender)
	handler := messenger.NewHandler(messageUseCase)
	streamServerInterceptor := grpc.NewInterceptor()
	serverBuilder := grpc.ServerBuilder{
		MessengerServer: handler,
		Interceptor:     streamServerInterceptor,
	}
	server := di.ProvideServer(serverBuilder)
	serverApplication := newApplication(server)
	return serverApplication
}
